[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Railway will automatically set PORT, but we can provide a default
[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
