[phases.setup]
nixPkgs = ["python3", "python3-pip", "build-essential", "libpq-dev"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt --no-cache-dir"
]

[phases.build]
cmds = [
    "echo 'Build phase completed'"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1" 