name: Deploy Backend to Railway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: "deploy-backend-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci --only=production
      
    - name: Run build
      run: npm run build
      
    - name: Install Railway CLI
      if: github.ref == 'refs/heads/main'
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        echo "$HOME/.railway/bin" >> $GITHUB_PATH
        
    - name: Deploy to Railway
      if: github.ref == 'refs/heads/main'
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        export RAILWAY_TOKEN="${{ secrets.RAILWAY_TOKEN }}"
        railway up --service web --detach